### ISSUE TITLE
rasa NLU json changes for next version

### ISSUE THREAD

**Issue by tmbo** [howdyai/botkit-rasa#1]
We changed the output format of the prediction (e.g. when calling `/parse`). 

```json
{
    "text": "I am looking for Chinese food",
    "entities": [
        {
          "start": 8,
          "end": 15,
          "value": "chinese",
          "entity": "cuisine"
        }
    ],
    "intent": {
        "confidence": 0.6485910906220309,
        "name": "restaurant_search"
    },
    "intent_ranking": [
        {
            "confidence": 0.6485910906220309,
            "name": "restaurant_search"
        },
        {
            "confidence": 0.14161531595656784,
            "name": "affirm"
        }
    ]
}
```

Would be cool if you could adapt this, so we don't break the integration :)

**Comment by sohlex** [comment]
Hi @tmbo,
since this project is lacking maintenance, i created [another one](https://github.com/sohlex/botkit-rasa). Is possible to use the middleware as an [npm package](https://www.npmjs.com/package/botkit-rasa). I also created a [PR in the Botkit documentation](https://github.com/howdyai/botkit/pull/886).

**Comment by fgr1986** [comment]
Hi @sohlex 
This middleware you created seems to be designed for rasa 0.7.
Related to what @tmbo states, does it works with the latest rasa  0.9.0a3 or stable (0.8)?

Regards

**Comment by sohlex** [comment]
Now it is updated to the new version. We can continue the discussion there :)

**Comment by peterswimm** [comment]
@sohlex Would you mind submitting any needed changes as a PR on this issue? We would love to keep this repo up to date if the community finds it useful.

**Comment by sohlex** [comment]
Sure, here it is: #2 :)

**Comment by gagan-bansal** [comment]
@sohlex Which repo should I use? This one https://github.com/howdyai/botkit-rasa or https://github.com/sohlex/botkit-rasa ?
npm module [botkit-rasa](https://www.npmjs.com/package/botkit-rasa) is linked with sohlex/botkit-rasa

**Comment by sohlex** [comment]
@gagan-bansal both repos are fine, newer changes are done on sohlex/botkit-rasa and later are merged on howdyai/botkit-rasa.

**Comment by gagan-bansal** [comment]
Thanks @sohlex for update.
